name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'

jobs:
  api_test:
    name: Run API Tests
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright API tests
        run: npx playwright test --config=playwright.api.config.ts
      - name: Upload Playwright API Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-api-report
          path: playwright-report/
          retention-days: 30
  ui_test:
    name: Run UI Tests
    runs-on: ubuntu-latest
    needs: api_test
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright UI tests
        run: npx playwright test --config=playwright.ui.config.ts
      - name: Upload Playwright UI Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-ui-report
          path: playwright-report/
          retention-days: 30